theme: jekyll-theme-chirpy
baseurl: ""
lang: en
timezone:

title: Flowing Thoughts
tagline: # subtitle
description: >-
  You are on the repository for my drafts, thoughts, guides and ideas.
  Please have a look around and take anything you like. Free of charge.

url: "https://blog.fabioiotti.com"

github:
  username: bruce965

#twitter:
#  username: twitter_username

social:
  name: Fabio Iotti
  email: fabiogiopla@gmail.com
  links:
    # first element serves as the copyright owner's link
    - https://github.com/bruce965
    #- https://twitter.com/username
    #- https://www.facebook.com/username
    #- https://www.linkedin.com/in/username

google_site_verification: # verification string

google_analytics:
  id: # Google Analytics ID

theme_mode: # [light|dark]

img_cdn:

avatar: assets/img/favicons/android-chrome-192x192.png

toc: true

comments:
  active: # e.g., 'disqus'; empty to disable
  #disqus:
  #  shortname: # Disqus shortname https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  #utterances: # https://utteranc.es/
  #  repo: # <gh-username>/<repo>
  #  issue_term: # < url | pathname | title | ...>
  #giscus: # https://giscus.app
  #  repo: # <gh-username>/<repo>
  #  repo_id:
  #  category:
  #  category_id:
  #  mapping: # optional, default to 'pathname'
  #  input_position: # optional, default to 'bottom'
  #  lang: # optional, default to the value of `site.lang`
  #  reactions_enabled: # optional, default to the value of `1`

assets:
  self_host:
    enabled: # boolean, empty means false
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
